[package]
name = "atm-fwhm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
crseo = "2.5.2"
dotenvy = "0.15.7"
env_logger.workspace = true
gmt_dos-clients_domeseeing = { workspace = true, features = ["object_store"], default-features = false }
indicatif.workspace = true
object_store = { version = "0.12.4", features = ["aws"] }
parse-monitors = { version = "0.3.2", path = "../.." }
serde = { workspace = true, features = ["derive"] }
serde-pickle.workspace = true
skyangle = "0.4.0"
tokio = { version = "1.49.0", features = ["full"] }


